version: '3.8'
services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            # - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php
        volumes:
            - ./:/var/www/html
            # - ./src:/var/www/html

    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: mysqlrootpass
            MYSQL_USER: mysqluser
            MYSQL_PASSWORD: mysqluserpass
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    mysql-data:
